// Copyright Nisse Group Ltd
// SPDX-License-Identifier: LicenseRef-TBD (see LICENSE decision note in README)

import { useEffect, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { fetchSnapshot, fetchStaticFallback } from "../api/client.js";
import type { SnapshotResponse } from "../api/types.js";
import { loadSnapshot, saveSnapshot, type StoredSnapshot } from "./snapshotStore.js";

/**
 * How the currently-shown snapshot was obtained:
 *  - "live":     fresh from the API.
 *  - "degraded": the API was unreachable, but the CDN-hosted static fallback
 *                (last-known status) was — an honest stale-but-real state.
 *  - "offline":  neither reachable; the device's own cached snapshot.
 */
export type CorridorMode = "live" | "degraded" | "offline";

export interface CorridorView {
  snapshot: SnapshotResponse | undefined;
  mode: CorridorMode;
  /** True whenever the shown data is not live (degraded or offline). */
  isStale: boolean;
  /** True only when neither the API nor the CDN fallback was reachable. */
  isOffline: boolean;
  /** True only before we have any data at all (live, fallback, or cached). */
  isLoading: boolean;
  /** ISO time the shown data was generated by the backend. */
  generatedAt: string | undefined;
  /** ISO time the corridor status was last confirmed (for the degraded banner). */
  confirmedAt: string | undefined;
  /** ISO time the device cache was stored (only when fully offline). */
  cachedAt: string | undefined;
  refetch: () => void;
}

/**
 * The heart of the offline / degraded story. Failing to a stale-but-honest state
 * is mandatory, so there are three tiers, in order:
 *
 *   1. Live API (/api/status/snapshot), persisted to IndexedDB on every success.
 *   2. CDN static fallback (regenerated by the backend on every status change) —
 *      reachable even when the whole backend is down. Shown behind a "service
 *      degraded — last confirmed at <time>" banner.
 *   3. The device's own last cached snapshot (fully offline).
 *
 * A stale snapshot is never presented as if it were live.
 */
export function useCorridor(): CorridorView {
  const [cached, setCached] = useState<StoredSnapshot | undefined>(undefined);
  const [cacheChecked, setCacheChecked] = useState(false);

  // Load any previously-cached snapshot once on mount.
  useEffect(() => {
    let alive = true;
    loadSnapshot().then((s) => {
      if (alive) {
        setCached(s);
        setCacheChecked(true);
      }
    });
    return () => {
      alive = false;
    };
  }, []);

  const live = useQuery({
    queryKey: ["snapshot"],
    queryFn: fetchSnapshot,
    refetchInterval: 60_000,
    refetchOnWindowFocus: true,
    retry: 1,
    staleTime: 30_000,
  });

  const liveFailed = !live.data && (live.isError || (live.isFetched && !live.isSuccess));

  // Only reach for the CDN fallback once the live fetch has actually failed.
  const fallback = useQuery({
    queryKey: ["snapshot-fallback"],
    queryFn: fetchStaticFallback,
    enabled: liveFailed,
    refetchInterval: liveFailed ? 60_000 : false,
    retry: 1,
    staleTime: 30_000,
  });

  // Persist whichever real snapshot we got so the device cache is always warm.
  useEffect(() => {
    const data = live.data ?? (liveFailed ? fallback.data : undefined);
    if (data) {
      void saveSnapshot(data);
      setCached({ snapshot: data, fetchedAt: new Date().toISOString() });
    }
  }, [live.data, fallback.data, liveFailed]);

  const liveSnap = live.isSuccess && live.data ? live.data : undefined;
  const fallbackSnap = liveFailed && fallback.isSuccess && fallback.data ? fallback.data : undefined;

  let mode: CorridorMode = "live";
  let snapshot: SnapshotResponse | undefined = liveSnap;
  if (!snapshot && fallbackSnap) {
    mode = "degraded";
    snapshot = fallbackSnap;
  } else if (!snapshot && cached?.snapshot) {
    mode = "offline";
    snapshot = cached.snapshot;
  }

  const isStale = mode !== "live" && Boolean(snapshot);
  const stillTryingFallback = liveFailed && fallback.isLoading;

  return {
    snapshot,
    mode,
    isStale,
    isOffline: mode === "offline",
    isLoading: !snapshot && (!cacheChecked || live.isLoading || stillTryingFallback),
    generatedAt: snapshot?.generatedAt,
    confirmedAt: snapshot?.corridor.updatedAt,
    cachedAt: mode === "offline" ? cached?.fetchedAt : undefined,
    refetch: () => {
      void live.refetch();
      if (liveFailed) void fallback.refetch();
    },
  };
}
