// Copyright Nisse Group Ltd
// SPDX-License-Identifier: LicenseRef-TBD (see LICENSE decision note in README)

import type {
  AdminOverride,
  AuditEntry,
  CommunityRequestItem,
  CreateRequestRequest,
  HealthReport,
  HistoryStatsResponse,
  IncidentsResponse,
  NotificationConfig,
  QueueReport,
  SnapshotResponse,
  StatusResponse,
  SubmitReportRequest,
  SubmitReportResponse,
  SubscribeRequest,
  SubscribeResponse,
  WebcamsResponse,
} from "./types.js";

/**
 * API base. Same-origin `/api` by default (the Vite dev server proxies to core,
 * and a same-host prod deploy serves both). For a static+CDN hub whose API lives
 * on another host, set `VITE_API_BASE` at build time (e.g. https://api.example).
 */
const API_BASE = (import.meta.env.VITE_API_BASE ?? "/api").replace(/\/$/, "");

/**
 * The CDN-hosted last-known-status file, regenerated by the backend on every
 * status change. It is served from the hub's own static host, so it stays
 * reachable even when the API/backend is completely down — the honest
 * stale-fallback source. Overridable with `VITE_STATIC_FALLBACK_URL`.
 */
const STATIC_FALLBACK_URL =
  import.meta.env.VITE_STATIC_FALLBACK_URL ?? `${import.meta.env.BASE_URL}status-fallback.json`;

/** Treat a slow backend as a failure so we can fall back to the cached snapshot. */
const REQUEST_TIMEOUT_MS = 6000;

async function getJson<T>(path: string, timeoutMs = REQUEST_TIMEOUT_MS): Promise<T> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetch(`${API_BASE}${path}`, {
      signal: controller.signal,
      headers: { accept: "application/json" },
    });
    if (!res.ok) {
      throw new Error(`Request failed: ${res.status} ${res.statusText}`);
    }
    return (await res.json()) as T;
  } finally {
    clearTimeout(timer);
  }
}

export function fetchStatus(): Promise<StatusResponse> {
  return getJson<StatusResponse>("/status");
}

export function fetchSnapshot(): Promise<SnapshotResponse> {
  return getJson<SnapshotResponse>("/status/snapshot");
}

/**
 * Fetch the CDN static fallback (last-known status) directly — bypasses API_BASE
 * so it works when the backend is down. Used only after a live fetch fails.
 */
export async function fetchStaticFallback(): Promise<SnapshotResponse> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), 4000);
  try {
    const res = await fetch(STATIC_FALLBACK_URL, {
      signal: controller.signal,
      headers: { accept: "application/json" },
      cache: "no-store",
    });
    if (!res.ok) throw new Error(`Fallback failed: ${res.status}`);
    return (await res.json()) as SnapshotResponse;
  } finally {
    clearTimeout(timer);
  }
}

/**
 * Health report. The endpoint returns 503 (with the full report body) when the
 * system is unhealthy, so we read the JSON on both 200 and 503 and only treat a
 * genuine transport/parse failure as an error.
 */
export async function fetchHealth(): Promise<HealthReport> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);
  try {
    const res = await fetch(`${API_BASE}/health`, {
      signal: controller.signal,
      headers: { accept: "application/json" },
    });
    if (res.status !== 200 && res.status !== 503) {
      throw new Error(`Health request failed: ${res.status}`);
    }
    return (await res.json()) as HealthReport;
  } finally {
    clearTimeout(timer);
  }
}

export function fetchHistoryStats(): Promise<HistoryStatsResponse> {
  return getJson<HistoryStatsResponse>("/history/stats");
}

export function fetchIncidents(activeOnly = true): Promise<IncidentsResponse> {
  return getJson<IncidentsResponse>(`/incidents${activeOnly ? "?active=1" : ""}`);
}

export function fetchWebcams(): Promise<WebcamsResponse> {
  return getJson<WebcamsResponse>("/webcams");
}

export class ApiError extends Error {
  constructor(
    public status: number,
    message: string,
  ) {
    super(message);
  }
}

/** Submit a public report. Throws ApiError(429) when rate-limited. */
export async function postReport(body: SubmitReportRequest): Promise<SubmitReportResponse> {
  const res = await fetch(`${API_BASE}/reports`, {
    method: "POST",
    headers: { "content-type": "application/json", accept: "application/json" },
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    const detail = (await res.json().catch(() => ({}))) as { message?: string };
    throw new ApiError(res.status, detail.message ?? `Request failed (${res.status})`);
  }
  return (await res.json()) as SubmitReportResponse;
}

// --- Community plane -------------------------------------------------------
export interface RequestFilter {
  incidentId?: string;
  segmentId?: string;
}

export function fetchRequests(filter: RequestFilter): Promise<{ requests: CommunityRequestItem[] }> {
  const params = new URLSearchParams();
  if (filter.incidentId) params.set("incidentId", filter.incidentId);
  if (filter.segmentId) params.set("segmentId", filter.segmentId);
  const qs = params.toString();
  return getJson<{ requests: CommunityRequestItem[] }>(`/requests${qs ? `?${qs}` : ""}`);
}

async function postJson<T>(path: string, body: unknown): Promise<T> {
  const res = await fetch(`${API_BASE}${path}`, {
    method: "POST",
    headers: { "content-type": "application/json", accept: "application/json" },
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    const detail = (await res.json().catch(() => ({}))) as { message?: string };
    throw new ApiError(res.status, detail.message ?? `Request failed (${res.status})`);
  }
  return (await res.json()) as T;
}

export function createRequest(body: CreateRequestRequest) {
  return postJson<{ ok: boolean; request: { id: string } }>("/requests", body);
}
export function addResponse(requestId: string, body: string, deviceToken?: string) {
  return postJson<{ ok: boolean }>(`/requests/${requestId}/responses`, { body, deviceToken });
}
export async function patchRequest(requestId: string, status: "matched" | "resolved", deviceToken: string) {
  const res = await fetch(`${API_BASE}/requests/${requestId}`, {
    method: "PATCH",
    headers: { "content-type": "application/json", accept: "application/json" },
    body: JSON.stringify({ status, deviceToken }),
  });
  if (!res.ok) throw new ApiError(res.status, `Request failed (${res.status})`);
  return (await res.json()) as { ok: boolean };
}
export function flagRequest(requestId: string) {
  return postJson<{ ok: boolean }>(`/requests/${requestId}/flag`, {});
}
export function flagResponse(responseId: string) {
  return postJson<{ ok: boolean }>(`/responses/${responseId}/flag`, {});
}

// --- Notifications ---------------------------------------------------------
export function fetchNotificationConfig(): Promise<NotificationConfig> {
  return getJson<NotificationConfig>("/notifications/config");
}
export function subscribe(body: SubscribeRequest): Promise<SubscribeResponse> {
  return postJson<SubscribeResponse>("/notifications/subscribe", body);
}
export async function unsubscribe(token: string): Promise<void> {
  await fetch(`${API_BASE}/notifications/unsubscribe`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ token }),
  });
}

// --- Admin (steward bearer token) -----------------------------------------
async function adminFetch<T>(path: string, token: string, init: RequestInit = {}): Promise<T> {
  const res = await fetch(`${API_BASE}${path}`, {
    ...init,
    headers: {
      accept: "application/json",
      authorization: `Bearer ${token}`,
      ...(init.body ? { "content-type": "application/json" } : {}),
      ...(init.headers ?? {}),
    },
  });
  if (!res.ok) throw new ApiError(res.status, `Request failed (${res.status})`);
  return (await res.json()) as T;
}

export const admin = {
  reports: (token: string, state = "pending") =>
    adminFetch<{ reports: QueueReport[] }>(`/admin/reports?state=${state}`, token),
  verify: (token: string, id: string) =>
    adminFetch<{ ok: boolean }>(`/admin/reports/${id}/verify`, token, { method: "POST" }),
  dismiss: (token: string, id: string, reason?: string) =>
    adminFetch<{ ok: boolean }>(`/admin/reports/${id}/dismiss`, token, {
      method: "POST",
      body: JSON.stringify({ reason }),
    }),
  merge: (token: string, reportIds: string[], targetIncidentId: string) =>
    adminFetch<{ ok: boolean; merged: number }>(`/admin/reports/merge`, token, {
      method: "POST",
      body: JSON.stringify({ reportIds, targetIncidentId }),
    }),
  overrides: (token: string) => adminFetch<{ overrides: AdminOverride[] }>(`/admin/overrides`, token),
  createOverride: (
    token: string,
    body: { segmentId: string; status: string; reason: string; expiresAt?: string },
  ) => adminFetch<{ ok: boolean }>(`/admin/overrides`, token, { method: "POST", body: JSON.stringify(body) }),
  clearOverride: (token: string, id: string) =>
    adminFetch<{ ok: boolean }>(`/admin/overrides/${id}`, token, { method: "DELETE" }),
  audit: (token: string) => adminFetch<{ entries: AuditEntry[] }>(`/admin/audit`, token),
  removeRequest: (token: string, id: string) =>
    adminFetch<{ ok: boolean }>(`/admin/requests/${id}/remove`, token, { method: "POST" }),
  removeResponse: (token: string, id: string) =>
    adminFetch<{ ok: boolean }>(`/admin/responses/${id}/remove`, token, { method: "POST" }),
};
